### PR TITLE
allow users to delete calendars via the UI

### PR DESCRIPTION
**Pull request by philandstuff**
instead of the rails console

I have not tested this in any way.. it might not even parse as valid
ruby for all i know

### CODE REVIEW

**Comment by tlwr** [comment]
assigned this to myself

**Comment by tlwr** [comment]
I'm gonna close this as this functionality is in https://github.com/alphagov/re-rotas/commit/e3bc3f2b77640cb91e34effcc856dddb2bdb7587 (albeit in a different form)

**Comment by philandstuff** [comment]
just before the 1 year anniversary of this PR 😄

**Comment by tlwr** [comment]
i am very efficient, as you can tell :trollface:

**Pull request closed without merging**
